context:
  name: sysroot_linux-32
  version: "2.12"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  # Using Ubuntu 20.04 (Focal) i386 glibc as the base
  url: http://archive.ubuntu.com/ubuntu/pool/main/g/glibc/libc6_2.31-0ubuntu9_i386.deb
  sha256: f3508da9bcd7b052df8e30d6c82902655809b68f8210edbc907b3fdc99d9b0ab

build:
  number: 1
  script:
    - mkdir -p ${PREFIX}/i686-conda_ubuntu-linux-gnu/sysroot
    - ar x *.deb
    - tar -xJf data.tar.xz -C ${PREFIX}/i686-conda_ubuntu-linux-gnu/sysroot

requirements:
  build:
    - binutils
    - tar
    - xz
  run: []

about:
  homepage: https://www.gnu.org/software/libc/
  license: LGPL-2.1-only
  summary: The GNU C Library (sysroot)
